### test login
POST http://localhost:3000/login
Content-Type: application/json

{
"email": "pipo@test.fr",
"password": "1234"
}


### Get Users

GET http://localhost:3000/login

### Get Promos

GET http://localhost:3000/promos


### ADD PROMOS

POST http://localhost:3000/promo
Content-Type: application/json

{
    "code":"test2",
    "start_date":"2021-04-15",
    "end_date":"2021-06-15",
    "pourcent" : 10
}